### PR TITLE
add missing pub

### PR DESCRIPTION
**Pull request by PSeitz**
Thanks for the crate! I'm currently evaluating different quantile algorithms for percentile aggregations in [tantivy](https://github.com/quickwit-oss/tantivy/) and so far this crate looks pretty good.

It still got some rough edges.
Without the exporting the types, the DDSketch struct can't be stored. Having to define `DDSketch<CubicallyInterpolatedMapping, CollapsingLowestDenseStore>,` is a odd API, so maybe it's better to hide these details and wrap them in a new type that gets exported.

```rust
use sketches_rust::index_mapping::CubicallyInterpolatedMapping;
use sketches_rust::store::CollapsingLowestDenseStore;
struct DDSketch2 {
    sketch: sketches_rust::DDSketch<CubicallyInterpolatedMapping, CollapsingLowestDenseStore>,
    error: f64,
    max_buckets: usize,
}

impl DDSketch {
    fn new(error: f64, max_buckets: usize) -> Self {
        Self {
            sketch: sketches_rust::DDSketch::collapsing_lowest_dense(error, max_buckets).unwrap(),
            error,
            max_buckets,
        }
    }
}

```

### CODE REVIEW

**Comment by loyispa** [comment]
Thanks for your pr and advice！ I have also been considering how to orgernized this part of the interface, some changes maybe made later.

**Comment by PSeitz** [comment]
Thanks for the fast publish!

The project I use for the comparison is here https://github.com/PSeitz/quantile_compare
Maybe it's useful to you.

What would be missing for using it in tantivy, would be a serialization with serde (we use json to send the results between nodes)

**Comment by loyispa** [comment]
serialization is on the way

**Comment by loyispa** [comment]
@PSeitz  serialization is already, have fun.

**Comment by PSeitz** [comment]
Awesome!

I noticed that you changed the API, but did publish as patch version `0.1.x`. For API changes rust uses semver, so it should be `0.2.0`, or it could break compilation on existing projects.

**Comment by loyispa** [comment]
Encode and Decode api is not stable before, so i just change it without upgrade 0.2.x.  I didn't think too much.

**Comment by PSeitz** [comment]
The breaking API change is not the encode API, but removing the exports from the submodules

**Comment by loyispa** [comment]
Thanks for your advice.  I have published the new v0.2 version as well as the new api which is easy to use. Maybe you could reconsider about it.

**Pull request merged**
